### ISSUE TITLE
Large barWidth with strokeCap round looks odd

### ISSUE THREAD

**Issue by large** [seosh817/Flutter_CircularSeekBar#1]
Thank you for this great widget! I am currently using it for a wattmeter.
I played around with different barWidths and found a bug, here is my code

```dart
            CircularSeekBar(
              interactive: false,
              width: double.infinity,
              height: 350,
              progress: _percent,
              minProgress: 0,
              maxProgress: 1,
              barWidth: 55,
              startAngle: 45,
              sweepAngle: 270,
              strokeCap: StrokeCap.round,
              trackColor: Colors.grey,
              progressGradientColors: const [Colors.green, Colors.yellow, Colors.red],
              //dashWidth: 80,
              //dashGap: 15,
              animation: true,
              animDurationMillis: 200,
            )
```

![image](https://user-images.githubusercontent.com/535446/216733830-e1e713fe-6bb9-438f-a674-f22de2834b70.png)

It looks OK with StrokeCap.butt, designwise a little more boring :) How about a strokeCap start / end instead?
That way you could have "butt" at the start and "round" at the end
![image](https://user-images.githubusercontent.com/535446/216733913-7e8b8545-dd0f-49c3-acc5-4e6afbba35fb.png)

If I changed the sweepangle to 360 I see clearly the gradient color-borders since it is clear red
![image](https://user-images.githubusercontent.com/535446/216734014-8cfb80f6-a85d-4686-aaf1-539a93ef2b22.png)

You have the best knowledge of this widget, any suggestions on how to fix it?

**Comment by seosh817** [comment]
![image](https://user-images.githubusercontent.com/43161981/216816113-ac95a802-d7ea-4601-8d39-3d5133544fa8.png)
Hi @large thanks for reporting the issue. 

I checked the problem, it seems to be a bug caused by not calculating the distance of the round cap when drawing a gradient with SweepGradient.

I didn't find the bug because I only tested the small size of barWidth. Thanks for reporting it.

The angle to put in the GradientRotation of SweepGradient is the theta value of the picture.

So I solved the problem by drawing a line from the center of the CircularSeekBar to the center of the roundCap, creating a right-angled trinagle by drawing a tangent line, and calculating the theta value with arcsin.

so, radius is right-angled triangle's hypotenuse, barwidth / 2 is its cathetus

![KakaoTalk_Image_2023-02-05-22-43-40](https://user-images.githubusercontent.com/43161981/216823275-9924d3f8-3cbd-4c1a-b8fa-4cd51c795ed9.jpeg)

code: GradientRotation(startAngleWithOffsetRadian - asin((barWidth / 2) / radius))

commit: b2807356d8049060f69bf1c5ad958c1e2c58307f

Can you confirm if the issue is resolved?

**Comment by seosh817** [comment]
Version 1.1.0 has been released.

**Comment by large** [comment]
Thank you for the quick feedback! I works great now 👍 
As a feature in the future you could add different custom strokecaps so it could look like a rounded arrow for instance.
